### ISSUE TITLE
Seems to be too dated and cannot talk to our server

### ISSUE THREAD

**Issue by yarikoptic** [karchie/arc-sync#1]
```shell
arc-sync$ ./arc-sync.py -h http://XXX.edu --proj YYY -u ZZZ -p "XXX"
Traceback (most recent call last):                              
  File "./arc-sync.py", line 8, in <module>                     
    map(lambda e: z.ZipFile(sio.StringIO(get('%(URI)s/scans/ALL/files?format=zip' % e)), 'r').extractall(opts['-l']), filter(lamb
ents' % opts))['ResultSet']['Result']))                         
  File "./arc-sync.py", line 8, in <lambda>                     
    map(lambda e: z.ZipFile(sio.StringIO(get('%(URI)s/scans/ALL/files?format=zip' % e)), 'r').extractall(opts['-l']), filter(lamb
ents' % opts))['ResultSet']['Result']))                         
KeyError: '-l'
```
most likely the script is too dated to talk to any recentish XNAT server.

**Comment by karchie** [comment]
@yarikoptic I don't have an XNAT handy to talk to, and I wouldn't be surprised if this is just too old, but: you need the -l (for location) argument to tell the script to where it should download things
